# Travis file for ROS 2.0
#   Author: Víctor Mayoral Vilches <victor@erlerobotics.com>

language: python

matrix:
    include:
        - os: linux
          sudo: true
          python: 3.5
          env: TOXENV=py35
        - os: osx
          language: generic
          env: PYTHON=3.5.1
          sudo: true
          osx_image: "xcode7.3"
          # osx_image: "xcode7.2"
          # osx_image: "xcode7"
          #osx_image: "xcode6.4"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - boost-latest
    packages:
      - g++-4.9
      - gcc-4.9
      - cmake
      - cmake-data
      - libboost1.55-all-dev

cache:
  ccache: true
  directories:
    - $HOME/opt

before_install:
  # - locale-gen en_US en_US.UTF-8 # set the locale
  # - sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash travis/before_install_linux.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash travis/before_install_osx.sh ; fi

install: 
  # - pip install nose
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  pip3 install pep8; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  pip3 install mock coverage empy vcstool; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install empy setuptools nose vcstool pep8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install pydocstyle pyflakes flake8 mock coverage ; fi

  # Get the ROS 2.0 packages into a workspace
  - mkdir -p $HOME/ros2_ws/src/ros2
  
  # # import from the local ros2.repos file
  # - vcs import ~/ros2_ws/src < ros2.repos
  
  # import from OSRF's official ros2.repos (from ros2/ros2)
  - git clone https://github.com/ros2/ros2
  - vcs import ~/ros2_ws/src < ros2/ros2.repos

  # Install cmake 3.5+
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://www.cmake.org/files/v3.5/cmake-3.5.2.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xf cmake-3.5.2.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd cmake-3.5.2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --prefix=/usr; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j 2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; fi

  # Disable/ignore selected packages
  - touch ~/ros2_ws/src/ros2/demos/image_tools/AMENT_IGNORE # image_tools
  - touch ~/ros2_ws/src/ros2/demos/intra_process_demo/AMENT_IGNORE # intra_process_demo

script:
  - export CXX=g++-4.9
  - export CC=gcc-4.9

  - cmake --version  
  - cd $HOME/ros2_ws/
  - src/ament/ament_tools/scripts/ament.py build